################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Aes.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Calibration.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Commands.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Csma.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_DirectRF.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_General.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Gpio.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Irq.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_LinearFifo.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Management.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_PktBasic.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_PktCommon.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_PktMbus.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_PktStack.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Qi.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Radio.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Timer.c \
C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Types.c 

OBJS += \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Aes.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Calibration.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Commands.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Csma.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_DirectRF.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_General.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Gpio.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Irq.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_LinearFifo.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Management.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktBasic.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktCommon.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktMbus.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktStack.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Qi.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Radio.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Timer.o \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Types.o 

C_DEPS += \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Aes.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Calibration.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Commands.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Csma.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_DirectRF.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_General.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Gpio.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Irq.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_LinearFifo.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Management.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktBasic.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktCommon.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktMbus.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktStack.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Qi.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Radio.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Timer.d \
./Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Types.d 


# Each subdirectory must supply rules for building sources it contributes
Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Aes.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Aes.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Calibration.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Calibration.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Commands.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Commands.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Csma.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Csma.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_DirectRF.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_DirectRF.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_General.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_General.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Gpio.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Irq.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Irq.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_LinearFifo.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_LinearFifo.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Management.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Management.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktBasic.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_PktBasic.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktCommon.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_PktCommon.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktMbus.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_PktMbus.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_PktStack.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_PktStack.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Qi.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Qi.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Radio.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Radio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Timer.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Timer.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Driver/BSP/Components/SPIRIT1/SPIRIT1_Driver/SPIRIT1_Library/SPIRIT_Types.o: C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Drivers/BSP/Components/spirit1/SPIRIT1_Library/Src/SPIRIT_Types.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -std=c99 -DSTM32L0 -DUSE_HAL_DRIVER -DSTM32L053xx -DNO_EEPROM -DP2P_DEMO -DSPIRIT1_ST_SHIELD -DUSE_SPIRIT1_DEFAULT -DNUCLEO_L053R8 -DSTM32 -DUSE_STM32L0XX_NUCLEO -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/X-NUCLEO-IDS01Ax/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/STM32L0xx_Nucleo" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Library/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../../../../../Drivers/BSP/Components/spirit1/SPIRIT1_Util/Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/../../../Inc" -I"C:/Users/adibacco/STM32CubeExpansion_SUBG1_V1.0.0/Projects/Multi/Examples/P2P_demo/SW4STM32/STM32L053R8-Nucleo/P2P_Demo/inc" -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


